apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthbridge
resources:
  - namespace.yaml
  - web.yaml 
  - hl7-service.yaml
  - monitoring-service.yaml
  - gateway.yaml
  - jaeger.yaml
configMapGenerator:
  - name: hb-config
    literals:
      - HL7_SERVICE_URL=http://hl7-service:5001
      - MONITORING_SERVICE_URL=http://monitoring-service:5002
      - WEB_SERVICE_URL=http://web:8081
      - GATEWAY_URL=http://gateway:8080
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - AWS_REGION=ca-central-1